#!/usr/bin/env python3

import rospy

from libelium_sensor_collector import ReadingThread


class Collector:

    def __init__(self):
        rospy.init_node("collector")
        rospy.loginfo("Launching collector node...")

        def callback(line: str):
            rospy.loginfo("Received: {}".format(line))
        self.reading_th = ReadingThread(rospy.get_param("~ip"), rospy.get_param("~port"), callback)
        self.reading_th.start()

        rospy.loginfo("Collector node is lanched!")

    def spin(self):
        rospy.spin()


if __name__ == "__main__":
    Collector().spin()

